ingress:
  ingressClassName: nginx
  enabled: true
  hosts:
    - host: echo.cluster.local
      paths:
        - /
  annotations:
    kubernetes.io/ingress.class: nginx
    #kubernetes.io/ingress.class: traefik
